---
title: "ForGabi"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, fig.height = 12, results="asis")
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(magrittr)
library(scales)
library(ggsci)
library(plotly)
library(hrbrthemes)
options(scipen=999)
```

```{r}
bound3 <- readRDS(file = "/Users/Ivanics/Desktop/GitHub/International-LDLT/Analysis/Forfigure/bound3forgraph.rds")

```

```{r What i showed you before}
bound2 <- bound3 %>% filter(DTYPE == "LDLT" & GRAFT_TYPE == "Segmental")

bound4 <- bound2 %>% filter(COUNTRY == "US" | COUNTRY == "UK" | COUNTRY == "CAN")
Trendsovertime <- bound4 %>% select(TX_YR, COUNTRY) 
Trendsovertime <- Trendsovertime %>% group_by(TX_YR, COUNTRY) %>% mutate(count = n())
Trendsovertime <- Trendsovertime %>% group_by(TX_YR) %>% mutate(countyr = n())
Trendsovertime <- Trendsovertime %>% mutate(percentage = count/countyr)

#Counts per year
ggplot(Trendsovertime, aes(factor(TX_YR), y = count, group = COUNTRY, 
                  color = COUNTRY)) +
  geom_line(size = 1.5, alpha = 0.8) +
  geom_point(size = 2) +
  scale_color_npg(name="Country") +
  #scale_color_brewer(name = "Etiology", palette = "Set1")+
  theme_test(base_size = 32) +
  xlab("Year of transplant") +
  ylab("Number of transplants") +
  scale_x_discrete(expand = expansion(mult = c(0, 0))) +
  scale_y_continuous(expand = expansion(mult = c(0, 0)), limits = c(0,350)) +
  annotate("text", x = 8, y = 70, label = "Canada: Cox-Stuart trend test p=0.49", size = 5) +
  annotate("text", x = 8, y = 20, label = "UK: Cox-Stuart trend test p=0.73", size = 5) +
  annotate("text", x = 6, y = 280, label = "US: Cox-Stuart trend test p=0.08", size = 5)

```

```{r Trying to optimize visualization}
#Here i create a count per year per country (how many transplants done per country per year)
COUNTYEAR <- bound3 %>% 
  group_by(TX_YR, COUNTRY) %>% 
  mutate(countYEAR = n()) %>% 
  ungroup()
COUNTYEAR <- COUNTYEAR %>% select(TX_YR, COUNTRY, countYEAR)


#here i subset to only living donor liver transplants, then group by year and country, and count (how many LDLTs done per country per year)
LDLT <- bound5 %>% filter(LDLT=="1" & GRAFT_TYPE == "Segmental") %>% group_by(TX_YR, COUNTRY) %>% mutate(countLDLT = n()) %>% ungroup()

#select only the variables i want
LDLT <- LDLT %>% select(TX_YR, COUNTRY, countLDLT) 

#keep only one year and country combination
LDLT <- distinct(TX_YR, COUNTRY)

#only keep one unique TX_YR and COUNTRY combo (so only one 2014 US for example) (for the LDLT only dataset)
unique_rows1 <- !duplicated(LDLT[c("TX_YR","COUNTRY")])
unique.df1 <- LDLT[unique_rows1,]

#same thing here (for the all transplant dataset)
unique_rows2 <- !duplicated(COUNTYEAR[c("TX_YR","COUNTRY")])
unique.df2 <- COUNTYEAR[unique_rows2,]

#merge the two by TX_YR and country, now there is a column of transplants per year, and another column of how many LDLTs per year
test <- merge(unique.df2, unique.df1, by=c("TX_YR", "COUNTRY"))
head(test)

#Trying plot
ggplot(test, aes(factor(TX_YR), y = countLDLT, group = COUNTRY, 
                  color = COUNTRY)) +
  geom_area(size = 1.5, alpha = 0.8, color_palette()) +
  geom_area(data=test, aes(factor(TX_YR), y=countYEAR, group = COUNTRY, color=COUNTRY), size = 1.5, alpha=0.1) +
  scale_color_jama(name="Country") +
  theme_test(base_size = 18) +
  xlab("Year of transplant") +
  ylab("Number of transplants") +
  facet_grid(.~COUNTRY, scales="free_y")+
  scale_x_discrete(expand = expansion(mult = c(0, 0)), breaks=seq(2008, 2018, 4)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0)), limits = c(0, 6660))
```

```{r gabi_dataprep}
# library(plotly)
# library(hrbrthemes)
# data preparation
# same essentially as what you have above, just created my own LDLT_only dataframe
# (my understanding of the data may need double checking from you, but
# if the bound3 source countains all cases then I think this should be correct)


bound3 <- readRDS(file = "./bound3forgraph.rds")

# From Tommy's implementation above:
#Here i create a count per year per country (how many transplants done per country per year)
COUNTYEAR <- bound3 %>% 
  group_by(TX_YR, COUNTRY) %>% 
  mutate(countYEAR = n()) %>% 
  ungroup()
COUNTYEAR <- COUNTYEAR %>% select(TX_YR, COUNTRY, countYEAR)
# Total transplants counts by year, by country, 2008-2018
total_transplants_country_year <- unique(COUNTYEAR)

# Total transplants counts  for living donors, according to
# additional filter of GRAFT_TYPE you used above,
# by year, by country, 2008-2018
LDLT_country_year <- bound3 %>%
  filter(DTYPE=="LDLT" & GRAFT_TYPE == "Segmental") %>% 
  group_by(TX_YR, COUNTRY) %>%
  mutate(countYEAR = n()) %>%
  ungroup() %>%
  select(TX_YR, COUNTRY, countYEAR) %>%
  unique()

# set aside the data we care about labeling
labeled_subset_LDLT_country_year <- subset(LDLT_country_year,
                                           TX_YR %in% c(2008, 2010, 2012, 2014, 2016, 2018))
labeled_subset_total_transplants_country_year <- subset(total_transplants_country_year, 
                                                        TX_YR %in% c(2008, 2010, 2012, 2014, 2016, 2018))

US_labeled_subset_LDLT_country_year <- filter(labeled_subset_LDLT_country_year, COUNTRY == "US")
US_labeled_subset_total_transplants_country_year <- filter(labeled_subset_total_transplants_country_year, COUNTRY=="US")

UK_labeled_subset_LDLT_country_year <- filter(labeled_subset_LDLT_country_year, COUNTRY == "UK")
UK_labeled_subset_total_transplants_country_year <- filter(labeled_subset_total_transplants_country_year, COUNTRY=="UK")

CAN_labeled_subset_LDLT_country_year <- filter(labeled_subset_LDLT_country_year, COUNTRY == "CAN")
CAN_labeled_subset_total_transplants_country_year <- filter(labeled_subset_total_transplants_country_year, COUNTRY=="CAN")



```


``` {r gabi_ggplot_faceted}
# ggplot object - faceted
ggp <- ggplot(NULL, aes(TX_YR, countYEAR)) +    # Draw ggplot2 plot based on two data frames
  geom_area(fill  ="antiquewhite2",
            alpha = 0.5, 
            data = total_transplants_country_year, 
            col = "antiquewhite2",
            mapping = aes(fill = "Total")) +

  geom_area(fill = "#b491c8", 
            alpha = 0.5, 
            data = LDLT_country_year, 
            mapping = aes(fill = "LDLT"),
            col = "#b491c8") +

  facet_grid(COUNTRY~., scales="free_y") +
  scale_x_continuous(limits = c(2008, 2018), 
                     breaks = c(2008, 2010, 2012, 2014, 2016, 2018))+
  scale_y_continuous(expand = expansion(mult = c(0, 0))) +
  
 
  # label the proportion of LDLT done for that year; label only 
  # the years of the x-axis breaks (to save space, optional ofc)
  # customize nudge amount for each country factor
  geom_text(data = US_labeled_subset_LDLT_country_year, 
             label = percent(US_labeled_subset_LDLT_country_year$countYEAR /
                               US_labeled_subset_total_transplants_country_year$countYEAR, 
                             accuracy = 0.1),
            size = 3,
            vjust = 0,
            nudge_y = 100,
            col = "#28193D",
            fontface = "bold") +
  geom_text(data = UK_labeled_subset_LDLT_country_year, 
             label = percent(UK_labeled_subset_LDLT_country_year$countYEAR /
                               UK_labeled_subset_total_transplants_country_year$countYEAR, 
                             accuracy = 0.1),
            size = 3,
            vjust = 0,
            nudge_y = 10,
            col = "#28193D",
            fontface = "bold") +
  geom_text(data = CAN_labeled_subset_LDLT_country_year, 
             label = percent(CAN_labeled_subset_LDLT_country_year$countYEAR /
                               CAN_labeled_subset_total_transplants_country_year$countYEAR, 
                             accuracy = 0.1),
            size = 3,
            vjust = 0,
            nudge_y = 5,
            col = "#28193D",
            fontface = "bold") +
  
  xlab("\nYear of transplant") +
  ylab("Number of transplants\n") +
 
  
  scale_color_manual("Legend Title", 
                     limits=c("Total transplants performed", "LDLT performed"), 
                     values = c("antiquewhite2","#28193D")) +
  theme_minimal() +
  theme(axis.title = element_text(size = 14, family = "serif"),
        strip.text.y = element_text(angle = 0, 
                                    size = 18,
                                    face = "bold",
                                    colour = "#28193D",
                                    family = "serif"),
        axis.text.x = element_text(size = 12, colour = "#424949"),
        axis.title.x = element_text(hjust = 0.95, colour = "#424949"),
        axis.title.y = element_text(angle = 90, hjust = 1, colour = "#424949"),
        axis.text.y = element_text(size = 8, colour = "#424949"), 
        panel.spacing.y = unit(3, "lines"),
        panel.grid.major = element_line(colour = "#F2F4F4"),
        panel.grid.minor = element_blank()) 
  

 
ggp

# ggplotly(ggp)
# flush_ticks(ggp)
  

# Saving with high res, importing the font that was used in the ipsum theme
# extrafont::font_import() # this command takes 1-2min (maybe move to start of script)
# extrafont::loadfonts()
# 
# # plot is scaled to 200% here but play with the size to see what works in the manuscript
ggsave(filename = "./proportional_transplants_by_year_country.png", device = "png", plot = ggp, scale = 2, dpi = "retina")

ggsave(filename = "./proportional_transplants_by_year_country.pdf", device = "pdf", plot = ggp, scale = 2, dpi = "retina")

# PS: if you hate the colours: https://urldefense.com/v3/__https://www.r-graph-gallery.com/42-colors-names.html__;!!CjcC7IQ!aJpQ4276B-YgypvS1PzrDkYoWy0setgdTJxjOlgpteCdl8fBPhjmQ2wQKL72KWFiqIw$ [r-graph-gallery[.]com]
```


``` {r gabi_ggplot_plotgrid}
#######
# SERIOUSLY CANNOT DISCOURAGE THIS APPROACH ENOUGH 
#######
#US DATA
# US_total_transplants_country_year <- total_transplants_country_year[total_transplants_country_year$COUNTRY == "US",]
# US_LDLT_country_year <- LDLT_country_year[LDLT_country_year$COUNTRY == "US",]
# US_labeled_subset_LDLT_country_year <- subset(US_LDLT_country_year,
#                                            TX_YR %in% c(2008, 2010, 2012, 2014, 2016, 2018))
# US_labeled_subset_total_transplants_country_year <- subset(US_total_transplants_country_year, 
#                                                         TX_YR %in% c(2008, 2010, 2012, 2014, 2016, 2018))
# #CAN DATA
# CAN_total_transplants_country_year <- total_transplants_country_year[total_transplants_country_year$COUNTRY == "CAN",]
# CAN_LDLT_country_year <- LDLT_country_year[LDLT_country_year$COUNTRY == "CAN",]
# CAN_labeled_subset_LDLT_country_year <- subset(CAN_LDLT_country_year,
#                                            TX_YR %in% c(2008, 2010, 2012, 2014, 2016, 2018))
# CAN_labeled_subset_total_transplants_country_year <- subset(CAN_total_transplants_country_year, 
#                                                         TX_YR %in% c(2008, 2010, 2012, 2014, 2016, 2018))
# #UK DATA
# UK_total_transplants_country_year <- total_transplants_country_year[total_transplants_country_year$COUNTRY == "UK",]
# UK_LDLT_country_year <- LDLT_country_year[LDLT_country_year$COUNTRY == "UK",]
# UK_labeled_subset_LDLT_country_year <- subset(UK_LDLT_country_year,
#                                            TX_YR %in% c(2008, 2010, 2012, 2014, 2016, 2018))
# UK_labeled_subset_total_transplants_country_year <- subset(UK_total_transplants_country_year, 
#                                                         TX_YR %in% c(2008, 2010, 2012, 2014, 2016, 2018))
# 
# p1 <- ggplot(NULL, aes(TX_YR, countYEAR)) +    # Draw ggplot2 plot based on two data frames
#   geom_area(fill  ="antiquewhite2",
#             alpha = 0.5, 
#             data = US_total_transplants_country_year, 
#             col = "antiquewhite2",
#             mapping = aes(fill = "Total")) +
#   geom_area(fill = rgb(0.2,0.1,0.5,0.2), 
#             alpha = 0.5, 
#             data = US_LDLT_country_year, 
#             mapping = aes(fill = "LDLT"),
#             col = "darkslateblue") +
#   facet_grid(COUNTRY~., scales="free_y") +
#   scale_x_continuous(limits = c(2008, 2018), 
#                      breaks = c(2008, 2010, 2012, 2014, 2016, 2018))+
#   scale_y_continuous(expand = expansion(mult = c(0, 0))) +
#   
#  
#   # label the proportion of LDLT done for that year; label only 
#   # the years of the x-axis breaks (to save space, optional ofc)
#   geom_text(data = US_labeled_subset_LDLT_country_year, 
#              label = percent(US_labeled_subset_LDLT_country_year$countYEAR /
#                                US_labeled_subset_total_transplants_country_year$countYEAR, 
#                              accuracy = 0.1),
#             size = 2,
#             # position = position_dodge(0.9),
#             # label.padding = unit(0.25, "lines"),
#             # vjust = "center",
#             # lineheight = 5,
#             nudge_y = 100,
#             col = "darkslateblue",
#             fontface = "bold") +
#   xlab("\nYear of transplant") +
#   ylab("Number of transplants\n") +
#   theme_minimal() +
#   theme(axis.title = element_text(size = 10, family = "serif"),
#         strip.text.y = element_text(angle = 0, 
#                                     size = 16,
#                                     face = "bold",
#                                     colour = "darkslateblue",
#                                     family = "serif"),
#         axis.text.x = element_text(face = "bold", size = 12, colour = "#515A5A"),
#         axis.title.x = element_text(hjust = 0.95, colour = "#424949"),
#         axis.title.y = element_text(angle = 90, hjust = 0.95, colour = "#424949"),
#         axis.text.y = element_text(colour = "#424949"), 
#         panel.spacing.y = unit(3, "lines"),
#         panel.grid.major = element_line(colour = "#F2F4F4"),
#         panel.grid.minor = element_blank()) 
# 
# 
# p1

```